<?xml version="1.0" encoding="utf-8"?><Database Name="Digital_Agriculture" Class="Environment_DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SKY-20160726ISM;Initial Catalog=Digital_Agriculture;Integrated Security=True;Pooling=False" SettingsObjectName="_3c_tcp.Properties.Settings" SettingsPropertyName="Digital_AgricultureConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.environemt_data" Member="environemt_data">
    <Type Name="environemt_data">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WiFi_name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="temp" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="humi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="co2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="light" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>