#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3c_tcp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DigitalAgritureCulture")]
	public partial class Environment_dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertEnv_Data(Env_Data instance);
    partial void UpdateEnv_Data(Env_Data instance);
    partial void DeleteEnv_Data(Env_Data instance);
    #endregion
		
		public Environment_dataDataContext() : 
				base(global::_3c_tcp.Properties.Settings.Default.DigitalAgritureCultureConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Environment_dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Environment_dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Environment_dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Environment_dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Env_Data> Env_Data
		{
			get
			{
				return this.GetTable<Env_Data>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Env_Data")]
	public partial class Env_Data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_;
		
		private string _WiFi_Name_;
		
		private System.DateTime _DataTime_;
		
		private System.Nullable<double> _Temperature_;
		
		private System.Nullable<double> _Humi_;
		
		private System.Nullable<double> _CO2_;
		
		private System.Nullable<double> _smokescope_;
		
		private System.Nullable<double> _light;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Changing(int value);
    partial void OnId_Changed();
    partial void OnWiFi_Name_Changing(string value);
    partial void OnWiFi_Name_Changed();
    partial void OnDataTime_Changing(System.DateTime value);
    partial void OnDataTime_Changed();
    partial void OnTemperature_Changing(System.Nullable<double> value);
    partial void OnTemperature_Changed();
    partial void OnHumi_Changing(System.Nullable<double> value);
    partial void OnHumi_Changed();
    partial void OnCO2_Changing(System.Nullable<double> value);
    partial void OnCO2_Changed();
    partial void Onsmokescope_Changing(System.Nullable<double> value);
    partial void Onsmokescope_Changed();
    partial void OnlightChanging(System.Nullable<double> value);
    partial void OnlightChanged();
    #endregion
		
		public Env_Data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_
		{
			get
			{
				return this._Id_;
			}
			set
			{
				if ((this._Id_ != value))
				{
					this.OnId_Changing(value);
					this.SendPropertyChanging();
					this._Id_ = value;
					this.SendPropertyChanged("Id_");
					this.OnId_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WiFi_Name_", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string WiFi_Name_
		{
			get
			{
				return this._WiFi_Name_;
			}
			set
			{
				if ((this._WiFi_Name_ != value))
				{
					this.OnWiFi_Name_Changing(value);
					this.SendPropertyChanging();
					this._WiFi_Name_ = value;
					this.SendPropertyChanged("WiFi_Name_");
					this.OnWiFi_Name_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataTime_", DbType="DateTime2 NOT NULL")]
		public System.DateTime DataTime_
		{
			get
			{
				return this._DataTime_;
			}
			set
			{
				if ((this._DataTime_ != value))
				{
					this.OnDataTime_Changing(value);
					this.SendPropertyChanging();
					this._DataTime_ = value;
					this.SendPropertyChanged("DataTime_");
					this.OnDataTime_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temperature_", DbType="Float")]
		public System.Nullable<double> Temperature_
		{
			get
			{
				return this._Temperature_;
			}
			set
			{
				if ((this._Temperature_ != value))
				{
					this.OnTemperature_Changing(value);
					this.SendPropertyChanging();
					this._Temperature_ = value;
					this.SendPropertyChanged("Temperature_");
					this.OnTemperature_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Humi_", DbType="Float")]
		public System.Nullable<double> Humi_
		{
			get
			{
				return this._Humi_;
			}
			set
			{
				if ((this._Humi_ != value))
				{
					this.OnHumi_Changing(value);
					this.SendPropertyChanging();
					this._Humi_ = value;
					this.SendPropertyChanged("Humi_");
					this.OnHumi_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO2_", DbType="Float")]
		public System.Nullable<double> CO2_
		{
			get
			{
				return this._CO2_;
			}
			set
			{
				if ((this._CO2_ != value))
				{
					this.OnCO2_Changing(value);
					this.SendPropertyChanging();
					this._CO2_ = value;
					this.SendPropertyChanged("CO2_");
					this.OnCO2_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smokescope_", DbType="Float")]
		public System.Nullable<double> smokescope_
		{
			get
			{
				return this._smokescope_;
			}
			set
			{
				if ((this._smokescope_ != value))
				{
					this.Onsmokescope_Changing(value);
					this.SendPropertyChanging();
					this._smokescope_ = value;
					this.SendPropertyChanged("smokescope_");
					this.Onsmokescope_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_light", DbType="Float")]
		public System.Nullable<double> light
		{
			get
			{
				return this._light;
			}
			set
			{
				if ((this._light != value))
				{
					this.OnlightChanging(value);
					this.SendPropertyChanging();
					this._light = value;
					this.SendPropertyChanged("light");
					this.OnlightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
